apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccountName: default
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16.2-debian-opensearch7-1.0
          env:
            - name: OPENSEARCH_HOST
              value: "https://vpc-aw-bootcamp-os-orvgpuz7skg4atunby6x2mr7ye.us-east-1.es.amazonaws.com"
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            - name: buffer
              mountPath: /var/log/fluentd-buffers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: buffer
          hostPath:
            path: /var/log/fluentd-buffers
            type: DirectoryOrCreate
        - name: fluentd-config
          configMap:
            name: fluentd-config
            items:
              - key: fluent.conf
                path: fluent.conf
